name: time_warden_flutter
description: "Time Warden Project - a Flutter-based time tracking app with Rust backend"

version: 1.0.1+1

publish_to: 'none' # Ensures that this package is not accidentally published to pub.dev

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Add any other dependencies you might need here. 
  # For example, if you are using state management, you might add provider or bloc.
  # provider: ^6.0.0
  # bloc: ^8.0.0
  # For FFI, you might need ffi package
  # ffi: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # If you have assets like images or fonts, define them here.
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #       - asset: assets/fonts/OpenSans-Bold.ttf
  #         weight: 700